[portinglayer] laundrywasher implementation
ambiot/ambz2_matter pull request #153
Opened 2023-08-24 10:29 UTC by xshuqun

* add laundrywasher example in portinglayer

2023-08-25 02:26 UTC, step0035 commented on component/common/application/matter/driver/opstate_driver.cpp
> +    else
testing

2023-08-25 07:24 UTC, SirRu24 reviewed
opstate_driver.cpp, opstate_driver.h, matter_drivers.cpp: Can change the style of pointer and reference declaration, not urgent
lib_chip_laundrywasher_core.mk, lib_chip_laundrywasher_mian.mk: Clean the commented out line, I am not sure if it was intended to be left here or forget to delete
zap file not tested yet

2023-08-25 07:24 UTC, SirRu24 commented on component/common/application/matter/example/laundrywasher/matter_drivers.cpp
> +void matter_driver_downlink_update_handler(AppEvent * event)
Update pointer format to int *ptr

2023-08-25 07:24 UTC, SirRu24 commented on component/common/application/matter/example/laundrywasher/matter_drivers.cpp
> +    downlink_event.mHandler = matter_driver_downlink_update_handler;
Equal signs are not aligned for matter_driver_set_opstate_callback, matter_driver_set_spinspeed_callback, matter_driver_set_rinses_callback, and matter_driver_set_mode_callback

2023-08-25 07:24 UTC, SirRu24 commented on component/common/application/matter/driver/opstate_driver.cpp
> +static RvcOperationalStateDelegate * gRvcOperationalStateDelegate = nullptr;
Line 104, 105, 121, 142, 143: Update pointer declaration to int *ptr format

2023-08-25 07:24 UTC, SirRu24 commented on component/common/application/matter/driver/opstate_driver.cpp
> +void GenericOperationalStateDelegateImpl::HandleStopStateCallback(GenericOperationalError & err)
Line 26, 36, 46, 60, 74, 88: update reference declaration style to GenericOperationalError &err format

2023-08-25 07:24 UTC, SirRu24 commented on component/common/application/matter/driver/opstate_driver.h
> +    Instance* GetOperationalStateInstance();
update pointer style to int *ptr format

2023-08-25 07:24 UTC, SirRu24 commented on component/common/application/matter/driver/opstate_driver.h
> +    void HandleStopStateCallback(GenericOperationalError & err) override;
Line 71, 77, 83, 89: update reference declaration to GenericOperationalError &err format

2023-08-25 07:24 UTC, SirRu24 commented on component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_core.mk
> +#CFLAGS += -DCONFIG_MATTER_BLEMGR_ADAPTER=1
Line 70, 184: clean commented out lines

2023-08-25 07:24 UTC, SirRu24 commented on component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_main.mk
> +#INCLUDES += -I$(SDKROOTDIR)/component/common/network/ssl/ssl_ram_map/rom
Line 14, 76: clean commented out commands

2023-08-25 07:28 UTC, step0035 commented on component/common/application/matter/example/laundrywasher/matter_drivers.cpp
> +    downlink_event.mHandler = matter_driver_downlink_update_handler;
equal sign alignment is fine, it is only enforced in connectedhomeip

2023-08-25 07:29 UTC, step0035 commented on component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_core.mk
> +#CFLAGS += -DCONFIG_MATTER_BLEMGR_ADAPTER=1
this is a special case of comment, can leave it in

2023-08-25 07:36 UTC, step0035 requested changes
no longer a placeholder implementation

2023-08-25 07:36 UTC, step0035 commented on component/common/application/matter/driver/opstate_driver.cpp
> +    // placeholder implementation
can delete this placeholder implementation as this is already our own implementation, might be misleading

2023-08-25 07:36 UTC, step0035 commented on component/common/application/matter/driver/opstate_driver.cpp
> +    // placeholder implementation
same =)

2023-08-25 07:36 UTC, step0035 commented on component/common/application/matter/driver/opstate_driver.cpp
> +    // placeholder implementation
same =))

2023-08-25 07:36 UTC, step0035 commented on component/common/application/matter/driver/opstate_driver.cpp
> +    // placeholder implementation
=)))

2023-08-31 01:07 UTC, SandyYeow approved these changes

2023-08-31 01:21 UTC, step0035 approved these changes

2023-09-04 03:31 UTC, SirRu24 approved these changes

2023-09-04 03:31 UTC, merged