[tools] add enhanced version of gen-certs.sh
ambiot/ambz2_matter pull request #156
Opened 2023-08-28 01:08 UTC by xshuqun

* Do not remove default gen-certs.sh as there are customer still using it.
* Enhanced version has added more arguments for vid, pid, existing paa_cert, existing paa_key, endproduct_vid and endproduct_pid
* Allows user to decide if PAI is vid-scoped, and how many DAC(s) should be generated
* Changed certification_type to 1
* resolves #25

2023-08-28 03:31 UTC, step0035 requested changes

2023-08-28 03:31 UTC, step0035 commented on tools/matter/factorydata/gen-certs-enhanced.sh
> +		"$chip_cert_tool" gen-att-cert --type a --subject-cn "Matter Test PAA" --subject-vid "$vid" --valid-from "$cert_valid_from" --lifetime "$cert_lifetime" --out-key "$paa_key_file".pem --out "$paa_cer
instead of commenting out the line to use an existing paa, is it better to have an optional input argument for the existing paa (like the endproduct_vid/pid)? if the existing paa is passed in as input, then skip the generating step

2023-08-28 03:36 UTC, step0035 commented on tools/matter/factorydata/gen-certs-enhanced.sh
> +		"$chip_cert_tool" gen-att-cert --type a --subject-cn "Matter Test PAA" --subject-vid "$vid" --valid-from "$cert_valid_from" --lifetime "$cert_lifetime" --out-key "$paa_key_file".pem --out "$paa_cer
remove comment

2023-08-28 03:37 UTC, step0035 commented on tools/matter/factorydata/gen-certs-enhanced.sh
> +	printf "./gen-certs.sh chip_dir chip_cert_tool vid pid paa_cert paa_key <endproduct_vid> <endproduct_pid>\n"
make `paa_key` and `paa_cert` optional also using `<>`

2023-08-28 03:58 UTC, step0035 approved these changes

2023-08-31 01:17 UTC, SandyYeow approved these changes

2023-08-31 01:22 UTC, step0035 approved these changes

2023-08-31 01:24 UTC, merged